name = "CGinJulia"
uuid = "a948f870-9853-11e9-2654-adce3b4b7690"
authors = ["Jack Snoeyink <snoeyink@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
