using Queryverse
"""
Creates a python file that can be run in Blender to generate a representation
of an object created by the CGinJulia package
"""

Code = String
pts = AbstractVector{Point3}

function Export()
Code = 'bl_info = {
    "name": "Convex Hull Generation in Julia",
    "author": "Jackson Meade (NCSSM) and Jack Snoeyink (UNC Chapel Hill)",
    "version": (1, 0),
    "blender": (2, 80, 0),
    "location": "View3D > Add > Mesh > Generated_Convex_Hull",
    "description": "Creates a Blender 2.8 format file to allow viewing of the convex hull generated by CGinJulia",
    "warning": "Please make sure you are familiar with the CGinJulia package before using this",
    "wiki_url": "github.com/snoeyink/CGinJulia",
    "category": "Add Convex Hull",
}


import bpy
from bpy.types import Operator
# from bpy.props import FloatVectorProperty
from bpy_extras.object_utils import AddObjectHelper, object_data_add
from mathutils import Vector


def represent_object(self, context):
   # scale_x = self.scale.x
   # scale_y = self.scale.y
'

end
